name: projectka_pos
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.1
  get: 4.6.5
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  unicons: ^2.1.0
  animate_icons: ^2.0.0
  pdf: ^3.8.3
  firebase_core: ^1.22.0
  encrypt: ^5.0.1
  cloud_firestore: ^3.4.7
  dropdown_search: ^5.0.2
  shimmer: ^2.0.0
  intl: ^0.17.0
  calendar_date_picker2: ^0.2.3
  loading_animation_widget: ^1.2.0+3
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/avatar/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
